server:
  port: 19999
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://localhost:8848/nacos/
    routes:
      - name: 订单服务
        serviceName: service-order
        location: /order/v2/api-docs?group=default
        servicePath: /
      - name: 用户体系
        serviceName: service-user
        location: /user/v2/api-docs?group=default
        servicePath: /
#  eureka:
#    enable: true
#    serviceUrl: http://localhost:11111/eureka/
#    routes:
#      - name: 订单服务
#        serviceName: service-order
#        location: /v2/api-docs?group=default
#        servicePath: /order
#      - name: 用户体系
#        serviceName: service-user
#        location: /aub/v2/api-docs?group=default
#        servicePath: /